#!/usr/bin/env python3
from argparse import ArgumentParser
from os import environ
from sys import stdout


def main(args):
    filter_fn   = eval(args["filter"])
    iterator_fn = eval(args["iterator"])

    for k, v in environ.items():
        if filter_fn(k, v):
            stdout.write(
                "{}\n".format(
                    iterator_fn(k, v)
                )
            )


if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument(
        "filter",
        help="Python expression to filter environment variables"
    )
    p.add_argument(
        "iterator",
        help="Python expression which will be called in each k:v pair"
    )

    main(p.parse_args().__dict__)
