#!/usr/bin/env python3
from argparse import ArgumentParser
from urllib.request import Request, urlopen
from re import split

units = {
    "Y": 10**24,
    "Z": 10**21,
    "E": 10**18,
    "P": 10**15,
    "T": 10**12,
    "G": 10**9,
    "M": 10**6,
    "k": 10**3,
}

def get(url):
    return urlopen(Request(url)).read()

def expand(args):
    nargs = args.copy()
    if not args["hashrate"].isnumeric():
        nargs["hashrate"] = args["hashrate"].rstrip("/s")
        nargs["hashrate"] = args["hashrate"].rstrip("H").rstrip("h")
        value, unit = [
            x
            for x in split(
                    "^([\d\.]+)([^\d]*)$",
                    nargs["hashrate"]
            )
            if x
        ]
        if unit not in units:
            raise KeyError("Unknown unit '{}'".format(unit))
        nargs["hashrate"] = float(value) / units[unit]
    else:
        nargs["hashrate"] = float(nargs["hashrate"])

    if args["difficulty"] == 0:
        nargs["difficulty"] = float(
            get("https://blockchain.info/q/getdifficulty").decode("utf8")
        )
    if args["reward_per_block"] == 0:
        nargs["reward_per_block"] = float(
            get("https://blockchain.info/q/bcperblock").decode("utf8")
        )

    return nargs

def main(args):
    identifier = "bitcoins-per-month = "
    print(
        identifier +
        (
            "(days-per-month * reward-per-block * hashrate * seconds-per-dat)"
            " / "
            "(difficulty * difficulty-offset)"
        )
    )
    print(
        identifier +
        (
            "({days_per_month} * {reward_per_block} * {hashrate} * {seconds_per_day})"
            " / "
            "({difficulty} * {difficulty_offset})"
        ).format(**args)
    )
    print(
        identifier +
        str(
            (args["days_per_month"] * args["reward_per_block"] * args["hashrate"] * args["seconds_per_day"]) /
            (args["difficulty"] * args["difficulty_offset"])
        )
    )

if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument(
        "--days-per-month",
        type=int,
        default=30,
        help="Number of days in each month"
    )
    p.add_argument(
        "--reward-per-block",
        type=float,
        default=0,
        help="Current network reward for each found block"
    )
    p.add_argument(
        "--hashrate",
        required=True,
        type=str,
        help=(
            "Amount of hashes per second you hardware could check. "
            "You could use values like `1234MH/s`, `1234MH`, `1234 MH` or just `1234` here. "
            "See: https://en.bitcoin.it/wiki/Hashrate"
        )
    )
    p.add_argument(
        "--seconds-per-day",
        type=int,
        default=60*60*24,
        help="Number of seconds in each day"
    )
    p.add_argument(
        "--difficulty",
        type=float,
        default=0,
        help=(
            "Measure of how difficult it is to find "
            "a hash below a given target. "
            "See: https://en.bitcoin.it/wiki/Difficulty"
        )
    )
    p.add_argument(
        "--difficulty-offset",
        type=int,
        default=(2**48/0xffff),
        help=(
            "See: https://en.bitcoin.it/wiki/Difficulty"
            "#What_network_hash_rate_results_in_a_given_difficulty.3F"
        )
    )

    main(
        expand(
            p.parse_args().__dict__
        )
    )
