#!/usr/bin/env python3
from argparse import ArgumentParser
from sys import stdin, stdout
from os.path import abspath, expanduser

empty_string = b""
new_line     = b"\n"

def read_file(path):
    if path == "-":
        return stdin.buffer.read()
    fullpath = abspath(
        expanduser(
            path
        )
    )
    with open(fullpath, "r") as file:
        return file.buffer.read()

def hex_to_str(file):
    data = read_file(file).strip()
    stdout.buffer.write(
        empty_string.join(
            chr(
                int(
                    data[x:x+2],
                    16
                )
            ).encode("utf-8")
            for x in range(
                    0,
                    len(data.decode("utf-8")),
                    2
            )
        ) + new_line
    )

if __name__ == "__main__":
    p = ArgumentParser(
        description="Convert hex string representation to raw string"
    )
    p.add_argument(
        "--file",
        help="File with data(default is stdin)",
        default="-"
    )
    hex_to_str(**p.parse_args().__dict__)
