#!/usr/bin/env python3
from argparse import ArgumentParser
from sys import stdin, stdout
from os.path import abspath, expanduser
from binascii import hexlify

empty_string = b""
new_line     = b"\n"

def read_file(path):
    if path == "-":
        return stdin.buffer.read()
    fullpath = abspath(
        expanduser(
            path
        )
    )
    with open(fullpath, "r") as file:
        return file.buffer.read()

def str_to_hex(file):
    data = read_file(file).strip()
    stdout.buffer.write(
        hexlify(data) + new_line
    )

if __name__ == "__main__":
    p = ArgumentParser(
        description="Convert string into hex representation"
    )
    p.add_argument(
        "--file",
        help="File with data(default is stdin)",
        default="-"
    )
    str_to_hex(**p.parse_args().__dict__)
