#!/usr/bin/env python3
from argparse import ArgumentParser
from os import execv, setgid, setuid, setgroups
from os.path import isabs
from sys import stdout, stderr
from pwd import getpwnam
from shutil import which


def demote(uid, gid):
    try:
        setgid(gid)
        setgroups([gid])
        setuid(uid)
    except Exception as e:
        stderr.write(
            "Failed to setuid:setgid to {}:{} - {}\n".format(
                uid,
                gid,
                e
            )
        )
        raise e

def execute(user, command=[]):
    entry = getpwnam(user)

    demote(
        entry.pw_uid,
        entry.pw_gid
    )

    cmd = command[0]
    if not isabs(cmd):
        cmd = which(cmd)

    stdout.write(
        "Running '{0}' as '{1}'".format(
            cmd,
            user
        )
    )

    execv(
        cmd,
        [cmd] + command[1:]
    )

if __name__ == "__main__":
    p = ArgumentParser(
        description="Setuid, setgid and exec"
    )

    p.add_argument(
        "--user",
        help="User name to setuid and setgid from",
        type=str
    )
    p.add_argument(
        "command",
        help="Command to exec(specify arguments after '--')",
        nargs="+"
    )

    execute(**p.parse_args().__dict__)
