#!/usr/bin/env python3
from argparse import ArgumentParser
from os import execv, setgid, setuid, setgroups
from os.path import isabs
from sys import stdout, stderr
from pwd import getpwnam
from shutil import which


def demote(uid, gid):
    try:
        setgid(gid)
        setgroups([gid])
        setuid(uid)
    except Exception as e:
        stderr.write(
            "Failed to setuid:setgid to {}:{} - {}\n".format(
                uid,
                gid,
                e
            )
        )
        raise e

def execute(args):
    user    = args["user"]
    command = args["command"]
    uid     = args["uid"]
    gid     = args["gid"]
    source  = args["source"]

    if source == "user":
        if user == "":
            raise ValueError(
                "Empty user name"
            )
        entry = getpwnam(user)
        uid   = entry.pw_uid
        gid   = entry.pw_gid
    elif source == "id":
        if uid < 0 or gid < 0:
            raise ValueError(
                "Negative uid or gid is not allowed"
            )
    else:
        raise ValueError(
            "Unknown source '{}'".format(source)
        )

    demote(
        uid,
        gid
    )

    cmd = command[0]
    if not isabs(cmd):
        cmd = which(cmd)

    stdout.write(
        "Running '{0}' as '{1}'".format(
            cmd,
            user
        )
    )

    execv(
        cmd,
        [cmd] + command[1:]
    )

if __name__ == "__main__":
    p = ArgumentParser(
        description="Setuid, setgid and exec"
    )

    p.add_argument(
        "--source",
        help=(
            "Source of data about user. "
            "You could use either 'user' or 'id'. "
            "`user` will get uid and gid for user name automatically. "
            "`id` will require manually specify `--uid` and `--gid`"
        ),
        default="user"
    )
    p.add_argument(
        "--user",
        help="User name to setuid and setgid from",
        type=str,
        default=""
    )
    p.add_argument(
        "--uid",
        help="User id for setuid",
        type=int,
        default=-1
    )
    p.add_argument(
        "--gid",
        help="Group id for setgid",
        type=int,
        default=-1
    )
    p.add_argument(
        "command",
        help="Command to exec(specify arguments after '--')",
        nargs="+"
    )

    execute(p.parse_args().__dict__)
